plugins = []
headers = []
redirects = []

[build]
edge_functions = "/Users/adrianbailador/Desktop/Projects Adri/wedding-app/netlify/edge-functions"
publish = "/Users/adrianbailador/Desktop/Projects Adri/wedding-app"
publishOrigin = "default"
command = "npm run build"
commandOrigin = "heuristics"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]